### ISSUE TITLE
Build issue - docker-compose

### ISSUE THREAD

**Issue by webyahoo** [AECgeeks/ifc-pipeline#7]
Tried the installation on multiple Docker environments and run into similar issues:

1. On AWS ubuntu instance, run the docker-compose, and get the following error message:

ubuntu@ip-abc:~/dev/ifc-pipeline$ sudo docker-compose up -d

Step 21/31 : COPY application/static /www/static/
 ---> Using cache
 ---> e2c4d49566da
**Step 22/31 : COPY application/bimsurfer/bimsurfer /www/static/bimsurfer
ERROR: Service 'frontend' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder365633164/application/bimsurfer/bimsurfer: no such file or directory**

**Comment by webyahoo** [comment]
Looks like the source Docker file directory does not exist. If the entire installation guide to the repository is only 2 lines, and we ran into multiple issues, how do we proceed from here?

ubuntu@ip-abce:~/dev/ifc-pipeline$ sudo ls /var/lib/docker/tmp/docker-builder365633164/
ls: cannot access '/var/lib/docker/tmp/docker-builder365633164/': No such file or directory

**Comment by aothms** [comment]
It's a git submodule. So you need to clone with `--recursive` or do a `git submodule init && git submodule update` after checkout. Sorry for the late reply.

**Comment by webdada** [comment]
Thanks @aothms. I run git commands you suggested and it updated the application submodule with new files. 

And the I run docker-compose and it completed (see log below). But no docker machines were created. If I run:
$docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
It show no docker machines are active. 



// console output:

.....
Step 30/31 : COPY application/queue.conf /etc/supervisord.conf
 ---> Using cache
 ---> 45bb7fd61765
Step 31/31 : WORKDIR /www
 ---> Using cache
 ---> 34926a444dc2
Successfully built 34926a444dc2
Successfully tagged ifc-pipeline_worker:latest
WARNING: Image for service worker was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating ifc-pipeline_certbot_1  ... done
Creating ifc-pipeline_db_1      ... done
Creating ifc-pipeline_redis_1   ... done
Creating ifc-pipeline_frontend_1 ... done
Creating ifc-pipeline_worker_1   ... done
Creating ifc-pipeline_nginx_1    ... done

**Comment by webdada** [comment]
As I am testing on the AWS ubuntu machine, I am expecting to use the localhost.
How to we access the web application via https//<ip_address>, or https://localhost?

ubuntu@ip-abc:~/dev/ifc-pipeline$ sudo ./init.sh def.com
docker: Error response from daemon: driver failed programming external connectivity on endpoint mystifying_jepsen (4df45da3943a183f934b61542ea03741925f9c49d4e0e3ba7da523ed1d9e4220): Bind for 0.0.0.0:80 failed: port is already allocated.

**Comment by aothms** [comment]
> But no docker machines were created

I'm not familiar with docker machine. `docker ps` should list the running containers. If you think there is some benefit to this project in using docker machine, feel free to send a Pull Request.

> Bind for 0.0.0.0:80 failed: port is already allocated.

init.sh starts a certbot image on port 80 for the https certificate. So make sure no other hosts are running (also not the pipeline docker compose (run `docker-compose down`).

> https//<ip_address>,

That doesn't exist afaict. httpS is always tied to a domain name. But you can use http://[ip-address]. If the compose is running.

Run `docker-compose logs` to see any issues.

**Comment by max482022** [comment]
Good afternoon. I have Nginx Proxy Manager configured for VM. Nginx in IFC pipeline may conflict?

**Comment by max482022** [comment]
Cert bot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: ifc.com
  Type:   unauthorized
  Detail: 195.58.243.240: Invalid response from https://ifc.com/.well-known/acme-challenge/8VG23y3w5sEIhPtAaUQZ6ulKbF4XN-zbj5myb6mFTv8: 404

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone web server started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more detail

**Comment by max482022** [comment]
Can Nginx be removed from IFC pepiline?

**Comment by max482022** [comment]
> 



> Поскольку я тестирую на машине AWS ubuntu, я ожидаю использовать localhost. Как получить доступ к веб-приложению через https //<ip_address> или https://localhost?
> 
> ubuntu @ip-abc: ~/dev/ifc-pipeline$ sudo ./init.sh def.com docker: Ответ на ошибку от демона: драйвер не смог запрограммировать внешнее подключение на конечной точке mystifying_jepsen (4df45da3943a183f934b61542ea03741925f9c49d4e0e3ba7da523ed1d9e4220): Привязка для 0.0.0.0: 80 не удалось: порт уже выделен.

Have you solved the problem?

**Comment by max482022** [comment]
Hello. Help please. After loading the IFC model, a window appears (Your conversion is in progress), but nothing happens. Here is the error:
IndexError: list index out of range
 - - [27/May/2022 05:54:58] "POST / HTTP/1.1" 200 -
 - - [27/May/2022 05:54:58] "GET /p/PWozsdIYYjpCQNrzXFouIoJkRDLvEhBW HTTP/1.1" 200 -
 - - [27/May/2022 05:54:58] "GET /static/main.css HTTP/1.1" 304 -
 - - [27/May/2022 05:54:58] "GET /static/ifcopenshell_0.png HTTP/1.1" 304 -
 - - [27/May/2022 05:54:58] "GET /static/ifcopenshell.gif HTTP/1.1" 404 -
 - - [27/May/2022 05:54:58] "GET /pp/zoXvDliaiUsWwhFUaKcqXlRmDqajfSCe HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/admin1/ifc/application/main.py", line 202, in get_progress
    model = session.query(database.model).filter(database.model.code == id).all()[0]
IndexError: list index out of range

**Comment by Gubanov-482022** [comment]
> Поскольку я тестирую на машине AWS ubuntu, я ожидаю использовать localhost. Как мы можем получить доступ к веб-приложению через https//<ip_address>, или https://localhost?
> 
> ubuntu@ip-abc:~/dev/ifc-pipeline$ sudo ./init.sh def.com docker: Ответ на ошибку от демона: драйвер не смог запрограммировать внешнее подключение на конечной точке mystifying_jepsen (4df45da3943a183f934b61542ea03741925f9c49d4e0e3ba7da523ed1d9e4220): Привязка для 0.0.0.0: 80 не удалось: порт уже выделен.

**Comment by Gubanov-482022** [comment]
hello. Have you solved this problem?

**Comment by Gubanov-482022** [comment]
> Поскольку я тестирую на машине AWS ubuntu, я ожидаю использовать localhost. Как мы можем получить доступ к веб-приложению через https//<ip_address>, или https://localhost?
> 
> ubuntu@ip-abc:~/dev/ifc-pipeline$ sudo ./init.sh def.com docker: Ответ на ошибку от демона: драйвер не смог запрограммировать внешнее подключение на конечной точке mystifying_jepsen (4df45da3943a183f934b61542ea03741925f9c49d4e0e3ba7da523ed1d9e4220): Привязка для 0.0.0.0: 80 не удалось: порт уже выделен.



> Поскольку я тестирую на машине AWS ubuntu, я ожидаю использовать localhost. Как мы можем получить доступ к веб-приложению через https//<ip_address>, или https://localhost?
> 
> ubuntu@ip-abc:~/dev/ifc-pipeline$ sudo ./init.sh def.com docker: Ответ на ошибку от демона: драйвер не смог запрограммировать внешнее подключение на конечной точке mystifying_jepsen (4df45da3943a183f934b61542ea03741925f9c49d4e0e3ba7da523ed1d9e4220): Привязка для 0.0.0.0: 80 не удалось: порт уже выделен.

hello. Have you solved this problem?

**Comment by max482022** [comment]
Step 13/25 : RUN python3 -m pip install -r requirements-production.txt
 ---> Running in 4a43a4675889
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c python3 -m pip install -r requirements-production.txt' returned a non-zero code: 1

How to solve the problem?

**Comment by aothms** [comment]
You should probably be able to add `--break-system-packages` to the docker command. Doesn't sound very reassuring, but should be ok within the very specific usage of such as docker container. If that resolves the problem feel free to send in a Pull Request.

**Comment by max482022** [comment]
How to add --break-system-packages to the docker command?

**Comment by aothms** [comment]
https://github.com/AECgeeks/ifc-pipeline/blob/4d26c33f79a2b67bd86d9f3f48d1ee7e8333c625/application/Dockerfile#L20

**Comment by max482022** [comment]
It helped, thanks,

# Python dependencies
RUN python3 -m pip install -r requirements-production.txt --break-system-packages
